### ISSUE TITLE
Make the collector crate public

### ISSUE THREAD

**Issue by popadi** [lambdalisue/rs-metrics-process#21]
Any chance to make the [`collector` ](https://github.com/lambdalisue/rs-metrics-process/blob/main/src/lib.rs#L99) sub-module public? I'm interested in using the `collect` method to retrieve an instance of a `Metrics` struct and then expose it.

Why? My app is using [prometheus/client_rust](https://github.com/prometheus/client_rust) instead of [metrics-exporter-prometheus](https://crates.io/crates/metrics-exporter-prometheus), so the metrics export needs to be a bit different (more info about the Collector trait [here](https://docs.rs/prometheus-client/latest/prometheus_client/registry/struct.Registry.html#method.register_collector), if you are interested). I could benefit from reusing some of the structs and functions defined in that sub-module.

**Comment by lambdalisue** [comment]
There is no particularly strong reason to do this, so if there is a PR with well-written documentation comments, we will review it 👍
