### ISSUE TITLE
`cpu_seconds_total` counter metric always reports `0`

### ISSUE THREAD

**Issue by zohnannor** [lambdalisue/rs-metrics-process#47]
#46 and https://github.com/lambdalisue/rs-metrics-process/releases/tag/v1.3.0 introduced a breaking change without major version bump, so users of the previous versions will unknowingly `cargo update` their dependencies and introduce a bug in their codebase. The new default behavior of `cpu_seconds_total` is not the same as the old one, as it is a counter reporting `absolute` values instread of the gauge.

After some testing, I figured it is still possible to get values greater than zero, but you'll have to load the CPU greatly. The main point is, the values reported by the metric are not the same as in the previous version I was relying on.

I propose yanking the affected versions and either:

a) Bump up the major version for the new version that introduced the breaking change;
b) Make the old behavior the default one.
c) Both of the above?

**Comment by lambdalisue** [comment]
Hum... The previous behavior was unintentional and #46 is kind a bug fix thus I did minor update. But your are right, that was a breaking change so I'll update the major.

**Comment by lambdalisue** [comment]
1.3.0 is yanked: https://crates.io/crates/metrics-process/1.3.0
2.0.0 is published: https://crates.io/crates/metrics-process/2.0.0

Thanks for your suggestion 👍
