### ISSUE TITLE
More metrics?

### ISSUE THREAD

**Issue by AMDmi3** [lambdalisue/rs-metrics-process#58]
There's a bunch of not yet supported metrics, for instance from `rusage`:

```
             long ru_minflt;          /* page reclaims */
             long ru_majflt;          /* page faults */
             long ru_inblock;         /* block input operations */
             long ru_oublock;         /* block output operations */
             long ru_nvcsw;           /* voluntary context switches */
             long ru_nivcsw;          /* involuntary context switches */
```

Some of these are also available in /proc, but proc and other system-specific structures contain even more values. Additionally `getrusage` can expose cumulative metrics for child processes.

What do you think of exposing (some of) these? If you're positive, what's your opinion on implementation details, in particular
- should we stick to metrics common to all systems, or is it ok to expose more system specific metrics?
- what if we need more dependencies? (for instance, I don't think all rusage metrics are available from procfs and we may need libc dependency for linux)

**Comment by lambdalisue** [comment]
Thank you for the suggestion. However, the purpose of this crate is to provide a cross-platform representation of Prometheus Process metrics, so including items that are not part of these metrics (especially those that are not cross-platform) would deviate from its intended scope.

That said, I understand the desire to access various metrics. If the internal structure of this crate is needed for creating a separate crate, we could consider making some of the internal structure public, as proposed in #21.

**Comment by AMDmi3** [comment]
Understandable, thank you. Won't you mind then if I fork this crate into something like `metrics-process-more` when/if I get to this? Internal structure of this crate would probably not be needed, as the fork would imply extending all of the internals (Metrics, Collector and the collectors code).

**Comment by AMDmi3** [comment]
Or maybe implement extra metrics here and hide these under a feature flag?

**Comment by lambdalisue** [comment]
> Understandable, thank you. Won't you mind then if I fork this crate into something like metrics-process-more when/if I get to this? 

Certainly, as long as it complies with the license, I have no objections. :+1:

> Or maybe implement extra metrics here and hide these under a feature flag?

As for implementing extra metrics here and hiding them behind a feature flag, I have considered that option. However, I’m concerned that adding code outside the crate’s intended scope could potentially compromise its stability. Therefore, even with a feature flag, I currently do not plan to include such changes.

**Comment by AMDmi3** [comment]
Got it, thank you again!
